### ISSUE TITLE
question about ownerAUTOReward

### ISSUE THREAD

**Issue by cryptolearner2021** [autofarmnetwork/AutofarmV2_CrossChain#1]
Hey guys,
I'm trying to understand your code and i got something i did not quite understand.

The owner auto reward is 12% on the website. i see this parameter down here [line 1454]

**uint256 public ownerAUTOReward = 138; // 12%**

that is used here [1594 - 1603]

**uint256 AUTOReward =multiplier.mul(AUTOPerBlock).mul(pool.allocPoint).div(totalAllocPoint);
AUTOToken(AUTOv2).mint(owner(), AUTOReward.mul(ownerAUTOReward).div(1000));
AUTOToken(AUTOv2).mint(address(this), AUTOReward);**

I see that it's applying 138/1000 that is 0.138 and sending to owner.

Is this the team 12% reward?

What i'm missing here?

**Comment by autofarm-network** [comment]
It should be 138/1138 :)
